E2E changes for main branch
google-developer-training/basic-android-kotlin-compose-training-unscramble pull request #118
Opened 2023-08-02 23:56 UTC by android-dev-lxl

2023-08-10 21:16 UTC, johnshea approved these changes
LGTM with some small changes.
- Upgrade to latest versions
- Check if `@file:Suppress("UnstableApiUsage")` can be removed from `build.gradle.kts (:app)` after upgrading versions
- In file `GameScreen.kt`, in function `GameScreenPreview`, it should be using a `Surface` so it matches how `MainActivity.kt` is coded.

2023-09-06 19:54 UTC, johnshea requested changes
Nav bar is not translucent but should be.

<img width="693" alt="Screenshot 2023-09-06 at 3 45 49 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/7107817/d38785ae-0b2f-4270-894e-faa07c1c782b">

2023-09-11 16:14 UTC, johnshea commented
Should the app name "Unscramble" be overlapping with the camera?

<img width="525" alt="Screenshot 2023-09-11 at 12 08 57 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/7107817/25e5d051-8e9d-4a45-8ff5-c913f1d94a8a">

Should the dialog be showing under the status bar?

<img width="904" alt="Screenshot 2023-09-11 at 12 05 51 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/7107817/c68fa0e0-2be5-440b-a8b0-34d8742ec6cf">

2023-09-11 23:49 UTC, android-dev-lxl commented
> Should the app name "Unscramble" be overlapping with the camera?
> 
> <img alt="Screenshot 2023-09-11 at 12 08 57 PM" width="525" src="https://user-images.githubusercontent.com/7107817/267081727-25e5d051-8e9d-4a45-8ff5-c913f1d94a8a.png">
> Should the dialog be showing under the status bar?
> 
> <img alt="Screenshot 2023-09-11 at 12 05 51 PM" width="904" src="https://user-images.githubusercontent.com/7107817/267081978-c68fa0e0-2be5-440b-a8b0-34d8742ec6cf.png">

I am not able to reproduce either.
<img width="467" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/24260141/092c6dd9-ad7f-4b43-a8fa-693bc8968906">


<img width="188" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/24260141/3fd5bbdd-850d-4e84-83af-7b98d2a942fe">

2023-09-18 18:48 UTC, johnshea commented
re: the dialog showing under status bar

To recreate - Use emulator "Pixel 6 API 33 w/ gesture navigation", turn emulator to landscape, click in the text edit box to enter your word

2023-09-18 18:51 UTC, johnshea requested changes
UI for edge-to-edge does not match the UI from branch `main` but it should.
<img width="1787" alt="Screenshot 2023-09-18 at 2 45 49 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-unscramble/assets/7107817/94d224fe-c9cb-48fd-b25e-9d495ad59376">

2023-10-16 15:10 UTC, johnshea requested changes

2023-10-16 15:10 UTC, johnshea commented on app/src/main/java/com/example/unscramble/ui/theme/Theme.kt
>  import android.app.Activity
Removed unused imports.

2023-10-16 15:10 UTC, johnshea commented on app/src/main/java/com/example/unscramble/ui/theme/Theme.kt
nit: line 100 - remove extra blank line.

2023-10-16 15:10 UTC, johnshea commented on app/src/main/java/com/example/unscramble/MainActivity.kt
> +            enableEdgeToEdge()
E2e api call is in the wrong spot. It should be before `super.onCreate()`

2023-10-17 19:38 UTC, johnshea approved these changes
lgtm

2024-01-29 23:23 UTC, merged